const constants = {
  FETCH_ORGANIZATIONS: 'FETCH_ORGANIZATIONS',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAIL: 'FETCH_FAIL',
  CLEAR_ORGANIZATIONS: 'CLEAR_ORGANIZATIONS',
}

export default constants;
